version: '3'
services:
  mongo1:
    image: mongo
    container_name: mongo1
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
    volumes:
      - volume-mongo1:/data/db


volumes:
  volume-mongo1:
  

      