version: "3.9"
services:
  mongodb:
    image: mongo
    container_name: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: hello
      MONGO_INITDB_ROOT_PASSWORD: world
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: hello 
      ME_CONFIG_MONGODB_ADMINPASSWORD: world 
      ME_CONFIG_MONGODB_SERVER: mongodb
    depends_on:
      - mongodb